// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20201104143351_proyecto3")]
    partial class proyecto3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("BlazorApp1.Data.Detalles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Recur")
                       .HasColumnType("INTEGER");

                    b.Property<int>("IdTarea")
                        .HasColumnType("INTEGER");


                    b.Property<int?>("Tarea")
                        .HasColumnType("INTEGER");

                    

                    b.HasKey("id");

                    b.HasIndex("Recur");

                    b.HasIndex("Tarea");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("BlazorApp1.Data.Recursos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("User")
                        .HasColumnType("INTEGER");

                    

                    b.HasKey("id");

                    b.HasIndex("User");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("BlazorApp1.Data.Tareas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                       .HasColumnType("TEXT");

                    b.Property<string>("vencimiento")
                       .HasColumnType("TEXT");

                    b.Property<string>("estimacion")
                       .HasColumnType("TEXT");

                    b.Property<int>("IdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("responsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                   


                    b.HasKey("id");

                    b.HasIndex("responsable");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("BlazorApp1.Data.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BlazorApp1.Data.Detalles", b =>
                {
                    b.HasOne("BlazorApp1.Data.Recursos", "Recur")
                        .WithMany()
                        .HasForeignKey("Recur");

                    b.HasOne("BlazorApp1.Data.Tareas", "Tarea")
                        .WithMany()
                        .HasForeignKey("Tarea");
                });

            modelBuilder.Entity("BlazorApp1.Data.Recursos", b =>
                {
                    b.HasOne("BlazorApp1.Data.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("User");
                });

            modelBuilder.Entity("BlazorApp1.Data.Tareas", b =>
                {
                    b.HasOne("BlazorApp1.Data.Recursos", "responsable")
                        .WithMany()
                        .HasForeignKey("responsable");
                });
#pragma warning restore 612, 618
        }
    }
}
